version: '2'
services:
  fetcher:
    build: .
    environment:
    - "SPRING_PROFILES_ACTIVE=production,app1"
    - "HOST=imap.gmx.net"
    - "PORT=993"
    - "USER=${USER}"
    - "PW=${PW}"
    - "PARSER_DIALECT=bike"
    ports:
    - 8281:8081