spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/autodb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

---
spring:
  profiles: preprod

  h2:
    console:
      enabled: false

  datasource:
    url: jdbc:mysql://192.168.178.67:3306/app1
    username: app1
    password: app1
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    database-plattform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

---
spring:
  profiles: app1

  h2:
    console:
      enabled: false

  datasource:
    url: jdbc:mysql://192.168.178.67:3306/app1
    username: app1
    password: app1
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    database-plattform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

---
spring:
  profiles: app2

  h2:
    console:
      enabled: false

  datasource:
    url: jdbc:mysql://192.168.178.67:3306/app2
    username: app2
    password: app2
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    database-plattform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

